### ISSUE TITLE
search by cancer types instead of tissues

### ISSUE THREAD

**Issue by emepyc** [emepyc/project-score#15]
Currently the user can search by tissue. When a tissue is selected the data page with a tissue filter is set. Since we are no going to use tissue filters but cancer type filters we need to change the behaviour of the searchbox.

**Comment by emepyc** [comment]
@Donnyvdm, while implementing this I noticed that the response for `cancer_types` does not include the `id`. For example:

```
{
   "cancer_types":
      {
         "count": 1,
         "hits": [
            {
               "name": "Breast Carcinoma",
                "type": "cancer_types"
            }
      ]
}
```
I'm missing the `id` of the cancer type (ie, 2). The `id` seems to be available for genes and models.
Is it possible to obtain that information?

**Comment by Donnyvdm** [comment]
Sure, are you after the id for the cancer type or the id for the analysis (those are two different things)?

**Comment by emepyc** [comment]
The same (numeric) id I get from the `analyses` endpoint. The rationale is that now that we can filter by analyses (although I'm wrongly calling them `cancer types`) we can link to the `table` page directly from the search setting the correct analysis to filter by.
