### ISSUE TITLE
Missing genes from website

### ISSUE THREAD

**Issue by Donnyvdm** [emepyc/project-score#23]
@emepyc Could you help me debug/fix this, please?

We received the following user feedback via e-mail:

> About three months back, we successfully downloaded a set of fitness score data with associated hyperlinks. However, we are unable to find data for some (but not all) of these genes if we searched the site for the same genes now. For example, previously saved hyperlink for TUBG1, https://score.depmap.sanger.ac.uk/gene/SIDG39953, could easily access the data. In contrast, if we directly search the site for TUBG1, we now get a sign, “no option”.  We have about 18 such genes for which previously saved hyperlinks are working, but none of these 18 molecules could be found directly in the live searchable engine (https://score.depmap.sanger.ac.uk/). Are these discrepancies are due to some kind of update?

> List of genes we are unable to locate now (but located and saved data earlier)
AR
ATOX1
CD19
FDPS
IL2RA
LIG3
POLA1
POLB
POLE
PSMB1
PSMB2
PSMB5
RPL3
RRM1
TOP1
TOP2A
TUBB
TUBG1

When I access the API directly, the data seems to be there, e.g.
https://api.cellmodelpassports.sanger.ac.uk/genes/SIDG38338?include=essentiality_profiles or
https://api.cellmodelpassports.sanger.ac.uk/genes/SIDG38338/datasets/crispr_ko

The website makes the following query which doesn't work:
https://api.cellmodelpassports.sanger.ac.uk//datasets/crispr_ko?agg={"fc_clean":["min","max"]}&filter=[{"name":"gene","op":"has","val":{"name":"id","op":"eq","val":"SIDG38338"}},{"name":"gene","op":"has","val":{"name":"essentiality_profiles","op":"any","val":{"name":"core_fitness_pancan","op":"eq","val":false}}}]&page[number]=1&page[size]=1

Removing the 'core_fitness_pancan' filter, does work:
https://api.cellmodelpassports.sanger.ac.uk//datasets/crispr_ko?agg={"fc_clean":["min","max"]}&filter=[{"name":"gene","op":"has","val":{"name":"id","op":"eq","val":"SIDG38338"}}]&page[number]=1&page[size]=1

It looks like we've introduced a bug when we made the `core_fitness_pancan=false` the default. I think that filter should only be applied to the model page, but not the gene page. 

Please let me know what you think and if you can find a way to fix it. I'll have a look at the search engine as well.

**Comment by emepyc** [comment]
Hi Donny,
I think this PR fixes the missing data in the gene page: 
https://github.com/emepyc/project-score/pull/24

But if I understand correctly the missing genes in the search needs to be fixed in the backend?

**Comment by Donnyvdm** [comment]
Yes you were correct and this is now fixed in the search engine on the backend too.

**Comment by emepyc** [comment]
Fixed in #24
